"use client";

import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Github } from "lucide-react";
import { projects } from "@/data/projects";

function ProjectVisual({ project }: { project: (typeof projects)[number] }) {
  const [index, setIndex] = useState(0);
  const image = project.screenshots[index];
  if (!image) return null;
  return <div><div className="window-frame group"><div className="window-bar"><i className="window-dot"/><i className="window-dot"/><i className="window-dot"/><span className="ml-auto mono text-[8px] uppercase tracking-[.12em] text-slate-600">Authentic product capture</span></div><div className="relative aspect-[16/10] overflow-hidden"><Image src={image.src} alt={image.alt} fill sizes="(max-width: 1024px) 100vw, 60vw" className="object-cover object-top transition-transform duration-700 group-hover:scale-[1.018]" priority={project.id === "supportpilot-ai"}/><div className="absolute inset-0 bg-gradient-to-t from-[#080b10]/45 to-transparent opacity-0 transition group-hover:opacity-100"/></div></div><div className="mt-4 flex gap-2 overflow-x-auto pb-1" role="tablist" aria-label={`${project.title} screenshot gallery`}>{project.screenshots.map((shot,i)=><button key={shot.src} role="tab" aria-selected={i===index} aria-label={`View screenshot ${i+1}: ${shot.alt}`} onClick={()=>setIndex(i)} className={`shrink-0 rounded-full px-3 py-2 mono text-[9px] transition ${i===index?"bg-[#63d9ff] text-[#061117]":"border hairline text-slate-500 hover:text-white"}`}>{String(i+1).padStart(2,"0")}</button>)}</div><p className="mt-3 text-xs leading-5 text-slate-500">{image.caption}</p></div>;
}

export function FeaturedProjects() {
  const featured = projects.filter(p=>p.featured);
  return <section id="projects" className="section-space border-b hairline"><div className="page-shell"><div className="max-w-3xl"><span className="eyebrow">Flagship systems</span><h2 className="section-title mt-5 text-balance">Work that proves<br/>the engineering.</h2><p className="mt-6 max-w-2xl text-base leading-7 text-slate-400">Three complete AI systems—presented through their real interfaces, architecture decisions, and recorded verification evidence.</p></div><div className="mt-20 space-y-32">{featured.map((project,index)=><article key={project.id} className={`grid items-center gap-10 lg:grid-cols-12 ${index===1?"lg:[&>*:first-child]:order-2":""}`}><div className="lg:col-span-5"><div className="flex items-center gap-3 mono text-[10px] uppercase tracking-[.14em] text-slate-600"><span className="text-[#63d9ff]">0{index+1}</span><span className="h-px w-8 bg-slate-800"/><span>{project.category}</span></div><h3 className="mt-5 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">{project.title}</h3><p className="mt-3 text-sm font-medium text-[#63d9ff]">{project.subtitle}</p><p className="mt-6 text-sm leading-7 text-slate-400">{project.problem}</p><div className="mt-7 grid grid-cols-2 gap-px overflow-hidden rounded-xl border hairline bg-[var(--line)]">{project.metrics.slice(0,4).map(m=><div key={m.label} className="bg-[#0b1018] p-4"><span className="mono text-lg font-semibold text-white">{m.value}</span><span className="mt-1 block text-[10px] uppercase tracking-wider text-slate-600">{m.label}</span></div>)}</div><div className="mt-6 flex flex-wrap gap-2">{project.technologies.slice(0,6).map(t=><span className="tech-pill mono" key={t}>{t}</span>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link href={`/projects/${project.slug}`} className="button-primary">Read case study <ArrowRight className="size-4"/></Link><a href={project.githubUrl} target="_blank" rel="noreferrer" className="button-secondary"><Github className="size-4"/>Source <ArrowUpRight className="size-3.5"/></a></div></div><div className="lg:col-span-7"><ProjectVisual project={project}/></div></article>)}</div></div></section>;
}
