import Link from "next/link";
import { ArrowRight, ArrowUpRight, Github } from "lucide-react";
import { projects } from "@/data/projects";
import { ProjectVisual } from "./ProjectVisual";

export function FeaturedProjects() {
  const featured = projects.filter(p=>p.featured);
  return <section id="projects" className="section-space border-b hairline"><div className="page-shell"><div className="max-w-3xl"><span className="eyebrow">Flagship systems</span><h2 className="section-title mt-5 text-balance">Work that proves<br/>the engineering.</h2><p className="mt-6 max-w-2xl text-base leading-7 text-slate-400">Three independent engineering projects—real interfaces, inspectable architecture, and historical verification records. Validation limits are disclosed in each case study.</p></div><div className="mt-20 space-y-32">{featured.map((project,index)=><article key={project.id} className={`grid items-center gap-10 lg:grid-cols-12 ${index===1?"lg:[&>*:first-child]:order-2":""}`}><div className="lg:col-span-5"><div className="flex items-center gap-3 mono text-[10px] uppercase tracking-[.14em] text-slate-600"><span className="text-[#63d9ff]">0{index+1}</span><span className="h-px w-8 bg-slate-800"/><span>{project.category}</span></div><h3 className="mt-5 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">{project.title}</h3><p className="mt-3 text-sm font-medium text-[#63d9ff]">{project.subtitle}</p><p className="mt-6 text-sm leading-7 text-slate-400">{project.problem}</p><p className="mt-4 text-xs leading-5 text-slate-400">{project.status}</p><div className="mt-7 grid grid-cols-2 gap-px overflow-hidden rounded-xl border hairline bg-[var(--line)]">{project.metrics.slice(0,4).map(m=><div key={m.label} className="bg-[#0b1018] p-4"><span className="mono text-lg font-semibold text-white">{m.value}</span><span className="mt-1 block text-[10px] uppercase tracking-wider text-slate-600">{m.label}</span></div>)}</div><div className="mt-6 flex flex-wrap gap-2">{project.technologies.slice(0,6).map(t=><span className="tech-pill mono" key={t}>{t}</span>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link href={`/projects/${project.slug}`} prefetch={false} className="button-primary">Read case study <ArrowRight className="size-4"/></Link><a href={project.githubUrl} target="_blank" rel="noreferrer" className="button-secondary"><Github className="size-4"/>Source <ArrowUpRight className="size-3.5"/></a></div></div><div className="lg:col-span-7"><ProjectVisual title={project.title} screenshots={project.screenshots}/></div></article>)}</div></div></section>;
}
