import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { projects, secondaryProjects } from "@/data/projects";

export function SecondaryProjects(){
 const biz=projects.find(p=>p.slug==="bizhunter-mis")!;
 const items=[{title:biz.title,category:"Desktop operations",description:biz.description,status:biz.status,technologies:biz.technologies.slice(0,4),href:"/projects/bizhunter-mis"},...secondaryProjects.filter(p=>["Trading Journal Pro X","LevelPilot Pro","Daybook Mobile Ledger"].includes(p.title)).map(p=>({...p,href:undefined}))];
 return <section id="additional-work" className="section-space border-b hairline"><div className="page-shell"><div className="grid gap-8 lg:grid-cols-2"><div><span className="eyebrow">Selected additional work</span><h2 className="section-title mt-5 text-balance">Range beyond<br/>the flagship systems.</h2></div><p className="max-w-xl self-end text-sm leading-7 text-slate-400">Local-first desktop software, trading infrastructure, operational analytics, and mobile ledgers—supporting breadth without competing with the core AI case studies.</p></div><div className="mt-14 divide-y divide-[var(--line)] border-y hairline">{items.map((item,i)=>{const content=<div className="group grid gap-4 py-7 transition sm:grid-cols-[4rem_1fr_1fr_auto] sm:items-center"><span className="mono text-[10px] text-slate-700">0{i+1}</span><div><p className="text-lg font-semibold tracking-tight group-hover:text-[#63d9ff]">{item.title}</p><p className="mt-1 mono text-[9px] uppercase tracking-wider text-slate-600">{item.category}</p><p className="mt-2 text-xs leading-5 text-[#63d9ff]">{item.status}</p></div><p className="text-xs leading-5 text-slate-400">{item.description}</p><div className="flex items-center gap-2"><span className="mono max-w-40 text-[10px] leading-5 text-slate-400">{item.technologies.slice(0,2).join(" · ")}</span>{item.href && <ArrowUpRight className="size-4 text-slate-600 transition group-hover:text-[#63d9ff]"/>}</div></div>;return item.href?<Link key={item.title} href={item.href} prefetch={false}>{content}</Link>:<div key={item.title}>{content}</div>})}</div></div></section>;
}
