import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { ArrowLeft, ArrowRight, ArrowUpRight, CheckCircle2, Github, LockKeyhole } from "lucide-react";
import { projects } from "@/data/projects";
import { siteConfig } from "@/data/site";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

interface Props{params:Promise<{slug:string}>}
export async function generateStaticParams(){return projects.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const p=projects.find(x=>x.slug===slug);if(!p)return{title:"Project Not Found"};return{title:`${p.title} Case Study`,description:p.description,openGraph:{title:`${p.title} — ${p.subtitle}`,description:p.description,url:`${siteConfig.url}/projects/${p.slug}`,images:p.screenshots[0]?[{url:p.screenshots[0].src}]:[]}}}

export default async function ProjectCaseStudyPage({params}:Props){
 const {slug}=await params;const project=projects.find(p=>p.slug===slug);if(!project)notFound();
 const index=projects.findIndex(p=>p.slug===project.slug);const next=projects[(index+1)%projects.length];
 return <><Navbar/><main className="pb-24 pt-28"><section className="page-shell"><Link href="/#projects" className="inline-flex items-center gap-2 mono text-[10px] uppercase tracking-[.14em] text-slate-500 hover:text-white"><ArrowLeft className="size-3.5"/>Back to selected work</Link><div className="mt-12 grid gap-10 lg:grid-cols-[1fr_.65fr]"><div><div className="flex items-center gap-3 mono text-[10px] uppercase tracking-[.14em] text-[#63d9ff]"><span>0{index+1}</span><span className="h-px w-8 bg-cyan-300/40"/><span>{project.category}</span></div><h1 className="display-title mt-6 text-balance">{project.title}</h1><p className="mt-5 text-lg font-medium text-slate-300">{project.subtitle}</p><p className="mt-7 max-w-3xl text-base leading-8 text-slate-400">{project.description}</p><div className="mt-8 flex flex-wrap gap-3"><a href={project.githubUrl} target="_blank" rel="noreferrer" className="button-primary"><Github className="size-4"/>Inspect repository <ArrowUpRight className="size-3.5"/></a><a href={siteConfig.resumeUrl} download className="button-secondary">Download resume</a></div></div><aside className="surface self-end rounded-2xl p-6"><span className="mono text-[9px] uppercase tracking-[.15em] text-slate-600">Verification record</span><div className="mt-5 grid grid-cols-2 gap-px overflow-hidden rounded-xl border hairline bg-[var(--line)]">{project.metrics.map(m=><div key={m.label} className="bg-[#0a0f17] p-4"><strong className="mono block text-lg text-white">{m.value}</strong><span className="mt-1 block text-[9px] uppercase tracking-wider text-slate-600">{m.label}</span></div>)}</div><p className="mt-4 text-[10px] leading-5 text-slate-600">Historical project evidence; not live production telemetry.</p></aside></div></section>

 {project.screenshots[0]&&<section className="page-shell mt-20"><div className="window-frame"><div className="window-bar"><i className="window-dot"/><i className="window-dot"/><i className="window-dot"/><span className="ml-auto mono text-[8px] uppercase tracking-wider text-slate-600">Product interface · authentic screenshot</span></div><div className="relative aspect-[16/9]"><Image src={project.screenshots[0].src} alt={project.screenshots[0].alt} fill priority sizes="100vw" className="object-cover object-top"/></div></div></section>}

 <section className="section-space border-b hairline"><div className="page-shell"><div className="grid gap-5 md:grid-cols-2"><article className="rounded-2xl border border-rose-300/10 bg-rose-300/[.025] p-7"><span className="mono text-[9px] uppercase tracking-[.15em] text-rose-300">Problem + constraints</span><h2 className="mt-4 text-2xl font-semibold tracking-tight">What had to be solved</h2><p className="mt-5 text-sm leading-7 text-slate-400">{project.problem}</p></article><article className="rounded-2xl border border-cyan-300/15 bg-cyan-300/[.025] p-7"><span className="mono text-[9px] uppercase tracking-[.15em] text-[#63d9ff]">Implementation</span><h2 className="mt-4 text-2xl font-semibold tracking-tight">How the system responds</h2><p className="mt-5 text-sm leading-7 text-slate-400">{project.solution}</p></article></div></div></section>

 <section className="section-space border-b hairline bg-white/[.012]"><div className="page-shell"><span className="eyebrow">System overview</span><h2 className="section-title mt-5">Architecture, stage by stage.</h2><div className="mt-12 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{project.architectureSteps.map((s,i)=><article key={s.step} className="surface relative min-h-56 rounded-2xl p-5"><span className="mono text-[10px] text-[#63d9ff]">{s.step}</span><h3 className="mt-8 text-base font-semibold">{s.title}</h3><p className="mt-3 text-xs leading-5 text-slate-500">{s.description}</p><p className="absolute bottom-5 left-5 mono text-[8px] uppercase tracking-wider text-slate-700">{s.technology}</p>{i<project.architectureSteps.length-1&&<ArrowRight className="absolute -right-2.5 top-1/2 z-10 hidden size-5 rounded-full bg-[#080b10] p-1 text-slate-600 xl:block"/>}</article>)}</div></div></section>

 {project.screenshots.length>1&&<section className="section-space border-b hairline"><div className="page-shell"><span className="eyebrow">Product walkthrough</span><h2 className="section-title mt-5">The system in use.</h2><div className="mt-12 grid gap-7 md:grid-cols-2">{project.screenshots.slice(1).map((s,i)=><figure key={s.src} className={`${i===0?"md:col-span-2":""}`}><div className="window-frame"><div className="relative aspect-[16/10]"><Image src={s.src} alt={s.alt} fill sizes={i===0?"100vw":"50vw"} className="object-cover object-top"/></div></div><figcaption className="mt-4"><strong className="text-sm font-medium text-white">{s.alt}</strong><p className="mt-1 text-xs leading-5 text-slate-500">{s.caption}</p></figcaption></figure>)}</div></div></section>}

 <section className="section-space border-b hairline bg-white/[.012]"><div className="page-shell grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><span className="eyebrow">Engineering decisions</span><h2 className="section-title mt-5">The important trade-offs.</h2><p className="mt-6 text-sm leading-7 text-slate-400">Detailed rationale is progressively disclosed so the case study stays readable without discarding technical depth.</p></div><div className="space-y-3">{project.deepDive.engineeringDecisions.map((d,i)=><details key={d.decision} open={i===0} className="group surface rounded-2xl p-5"><summary className="cursor-pointer list-none pr-8 text-sm font-semibold marker:hidden">{d.decision}<span className="float-right text-[#63d9ff] group-open:rotate-45">+</span></summary><div className="mt-5 grid gap-4 border-t hairline pt-5 sm:grid-cols-2"><div><span className="mono text-[9px] uppercase tracking-wider text-slate-600">Rationale</span><p className="mt-2 text-xs leading-6 text-slate-400">{d.rationale}</p></div><div><span className="mono text-[9px] uppercase tracking-wider text-[#63d9ff]">Impact</span><p className="mt-2 text-xs leading-6 text-slate-400">{d.impact}</p></div></div></details>)}</div></div></section>

 <section className="section-space"><div className="page-shell grid gap-8 lg:grid-cols-2"><div className="surface rounded-3xl p-7"><div className="flex items-center gap-3"><LockKeyhole className="size-5 text-[#63d9ff]"/><h2 className="text-2xl font-semibold">Security &amp; validation</h2></div><ul className="mt-7 space-y-3">{project.deepDive.securityAndGovernance.map(x=><li key={x} className="flex gap-3 text-xs leading-6 text-slate-400"><CheckCircle2 className="mt-1 size-3.5 shrink-0 text-emerald-400"/>{x}</li>)}</ul></div><div className="surface rounded-3xl p-7"><span className="mono text-[9px] uppercase tracking-wider text-slate-600">Technical stack</span><div className="mt-6 flex flex-wrap gap-2">{project.technologies.map(t=><span key={t} className="tech-pill mono">{t}</span>)}</div><div className="mt-8 border-t hairline pt-6"><span className="mono text-[9px] uppercase tracking-wider text-[#63d9ff]">Engineering takeaway</span><p className="mt-3 text-sm italic leading-7 text-slate-300">“{project.deepDive.lessonsLearned}”</p></div></div></div><div className="mt-20 flex flex-col items-start justify-between gap-5 border-t hairline pt-8 sm:flex-row sm:items-center"><Link href="/" className="inline-flex items-center gap-2 text-xs text-slate-500 hover:text-white"><ArrowLeft className="size-3.5"/>Return to portfolio</Link><Link href={`/projects/${next.slug}`} className="inline-flex items-center gap-2 text-sm font-semibold text-[#63d9ff]">Next case study: {next.title}<ArrowRight className="size-4"/></Link></div></section>
 </main><Footer/></>;
}
