"use client";

import { useId, useState } from "react";
import { ArrowRight, Check } from "lucide-react";
import { capabilities } from "@/data/capabilities";
import { navigateTabs } from "@/lib/tab-navigation";

export function Capabilities() {
  const [active, setActive] = useState(0);
  const panelId = useId();
  const item = capabilities[active];
  return <section id="capabilities" className="section-space border-b hairline"><div className="page-shell grid gap-12 lg:grid-cols-[.78fr_1.22fr]"><div><span className="eyebrow">Core capabilities</span><h2 className="section-title mt-5 text-balance">Systems, not<br/>AI theatre.</h2><p className="mt-6 max-w-md text-sm leading-7 text-slate-400">Demonstrated capabilities from shipped project code: deterministic boundaries around probabilistic models, explicit evidence, and reversible human control.</p><div className="mt-10 space-y-1" role="tablist" aria-orientation="vertical" aria-label="Engineering capabilities">{capabilities.map((cap,i)=><button role="tab" id={`${panelId}-tab-${i}`} aria-controls={panelId} tabIndex={active===i?0:-1} aria-selected={active===i} key={cap.id} onClick={()=>setActive(i)} onKeyDown={event => navigateTabs(event, i, capabilities.length, setActive)} className={`group flex w-full items-center justify-between border-b hairline py-4 text-left text-sm transition ${active===i?"text-white":"text-slate-500 hover:text-slate-300"}`}><span><span className="mono mr-4 text-[9px] text-slate-700">0{i+1}</span>{cap.title}</span><ArrowRight className={`size-3.5 transition ${active===i?"translate-x-0 text-[#63d9ff]":"-translate-x-2 opacity-0"}`}/></button>)}</div></div><div id={panelId} role="tabpanel" aria-labelledby={`${panelId}-tab-${active}`} className="surface relative min-h-[500px] overflow-hidden rounded-3xl p-7 sm:p-10"><div className="absolute inset-0 grid-bg opacity-25"/><div className="relative"><span className="mono text-[10px] uppercase tracking-[.15em] text-[#63d9ff]">Capability 0{active+1}</span><h3 className="mt-6 max-w-xl text-3xl font-semibold tracking-[-.04em] sm:text-4xl">{item.title}</h3><p className="mt-3 text-sm font-medium text-slate-300">{item.tagline}</p><p className="mt-7 max-w-2xl text-sm leading-7 text-slate-400">{item.description}</p><div className="mt-10 border-t hairline pt-7"><p className="mono text-[9px] uppercase tracking-[.16em] text-slate-600">Evidence in the work</p><ul className="mt-5 grid gap-3 sm:grid-cols-2">{item.keySignals.map(signal=><li key={signal} className="flex items-start gap-3 rounded-xl border hairline bg-black/20 p-4 text-xs leading-5 text-slate-300"><Check className="mt-0.5 size-3.5 shrink-0 text-[#63d9ff]"/>{signal}</li>)}</ul></div><div className="mt-8 flex flex-wrap gap-2">{item.technologies.map(t=><span key={t} className="tech-pill mono">{t}</span>)}</div></div></div></div></section>;
}
