"use client";

import { useState } from "react";
import { ArrowRight, CheckCircle2 } from "lucide-react";

const stages = [
  { title: "Input received", tech: "n8n · REST · Forms", copy: "A typed payload enters through an explicit API contract rather than passing raw text directly to a model." },
  { title: "Payload validation", tech: "Pydantic v2", copy: "Schema checks normalize fields, enforce boundaries, and quarantine suspicious instructions before orchestration." },
  { title: "Context retrieval", tech: "FTS5 · pgvector", copy: "Relevant, provenance-linked evidence is retrieved with thresholds and citation identifiers." },
  { title: "LLM routing", tech: "Provider circuit breaker", copy: "A controlled router selects an available provider for semantic extraction and handles upstream failure." },
  { title: "Decision logic", tech: "Deterministic Python", copy: "Business rules, scores, SLA tiers, and risk limits are computed in code—not improvised by the LLM." },
  { title: "Human approval", tech: "HITL state gate", copy: "Low-confidence or high-impact actions enter a visible suspension state for review and editing." },
  { title: "Output + audit", tech: "Idempotency · SHA-256", copy: "Approved work dispatches once, with the decision path and operator actions recorded for inspection." },
];

export function WorkflowExplorer() {
  const [active,setActive]=useState(0); const stage=stages[active];
  return <section id="workflow" className="section-space border-b hairline bg-white/[.012]"><div className="page-shell"><div className="grid items-end gap-8 lg:grid-cols-2"><div><span className="eyebrow">Interactive engineering walkthrough</span><h2 className="section-title mt-5 text-balance">Inside an AI<br/>automation workflow.</h2></div><p className="max-w-xl text-sm leading-7 text-slate-400 lg:justify-self-end">An illustrative reliability pattern distilled from the documented architecture of SupportPilot AI, the Lead Management Agent, and OpsForge AI. It does not represent live telemetry.</p></div><div className="surface mt-14 overflow-hidden rounded-3xl"><div className="grid lg:grid-cols-[1fr_.72fr]"><div className="relative border-b hairline p-5 sm:p-8 lg:border-b-0 lg:border-r"><div className="absolute inset-0 grid-bg opacity-20"/><div className="relative space-y-2">{stages.map((s,i)=><button key={s.title} onClick={()=>setActive(i)} onFocus={()=>setActive(i)} className={`group relative flex min-h-16 w-full items-center gap-4 rounded-xl border p-3 text-left transition sm:p-4 ${i===active?"border-cyan-300/50 bg-cyan-300/[.07]":"border-transparent hover:border-white/10 hover:bg-white/[.02]"}`}><span className={`grid size-8 shrink-0 place-items-center rounded-full mono text-[10px] ${i<=active?"bg-[#63d9ff] text-[#071118]":"border hairline text-slate-600"}`}>{i<active?<CheckCircle2 className="size-4"/>:String(i+1).padStart(2,"0")}</span><span><strong className={`block text-sm ${i===active?"text-white":"text-slate-400"}`}>{s.title}</strong><span className="mono mt-1 block text-[9px] uppercase tracking-wider text-slate-600">{s.tech}</span></span>{i<stages.length-1&&<span aria-hidden className={`absolute -bottom-3.5 left-[1.85rem] h-5 w-px ${i<active?"bg-[#63d9ff]":"bg-slate-800"}`}/>}</button>)}</div></div><div className="flex min-h-[390px] flex-col justify-between p-7 sm:p-10"><div><span className="mono text-[10px] uppercase tracking-[.16em] text-[#63d9ff]">Selected stage · {String(active+1).padStart(2,"0")}</span><h3 className="mt-6 text-3xl font-semibold tracking-[-.04em]">{stage.title}</h3><p className="mt-3 mono text-[10px] uppercase tracking-wider text-slate-500">{stage.tech}</p><p className="mt-8 text-sm leading-7 text-slate-400">{stage.copy}</p></div><div className="mt-10 flex items-center justify-between border-t hairline pt-6"><span className="mono text-[9px] uppercase text-slate-600">Illustrative system state</span><button onClick={()=>setActive((active+1)%stages.length)} className="inline-flex items-center gap-2 text-xs font-semibold text-[#63d9ff]">Next stage <ArrowRight className="size-3.5"/></button></div></div></div></div></div></section>;
}
